_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 2
                - 13
                - 14
                - 55
            "4": 3.10.16
            "5": 0.20.0
            "12": 0.20.0
            "13": darwin-arm64
algorithm_config:
    value:
        clip_epsilon: 0.2
        critic_coef: 1
        entropy_coef: 0
        lmbda: 0.9
        loss_critic_type: l2
        minibatch_advantage: false
        scale_mapping: biased_softplus_1.0
        share_param_critic: true
        use_tanh_normal: true
algorithm_name:
    value: mappo
continuous_actions:
    value: true
critic_model_config:
    value:
        _is_critic: true
        activation_class: torch.nn.modules.activation.Tanh
        activation_kwargs: null
        layer_class: torch.nn.modules.linear.Linear
        norm_class: null
        norm_kwargs: null
        num_cells:
            - 256
            - 256
critic_model_name:
    value: mlp
environment_name:
    value: powergridworld
experiment_config:
    value:
        adam_eps: 1e-06
        buffer_device: cpu
        checkpoint_at_end: false
        checkpoint_interval: 0
        clip_grad_norm: true
        clip_grad_val: 5
        collect_with_grad: false
        create_json: true
        evaluation: true
        evaluation_deterministic_actions: true
        evaluation_episodes: 10
        evaluation_interval: 120000
        evaluation_static: false
        exploration_anneal_frames: null
        exploration_eps_end: 0.01
        exploration_eps_init: 0.8
        gamma: 0.99
        hard_target_update_frequency: 5
        keep_checkpoints_num: 3
        loggers:
            - csv
            - wandb
        lr: 5e-05
        max_n_frames: 3000000
        max_n_iters: null
        off_policy_collected_frames_per_batch: 6000
        off_policy_init_random_frames: 0
        off_policy_memory_size: 1000000
        off_policy_n_envs_per_worker: 10
        off_policy_n_optimizer_steps: 1000
        off_policy_prb_alpha: 0.6
        off_policy_prb_beta: 0.4
        off_policy_train_batch_size: 128
        off_policy_use_prioritized_replay_buffer: false
        on_policy_collected_frames_per_batch: 6000
        on_policy_minibatch_size: 400
        on_policy_n_envs_per_worker: 10
        on_policy_n_minibatch_iters: 45
        parallel_collection: false
        polyak_tau: 0.005
        prefer_continuous_actions: true
        project_name: benchmarl
        render: true
        restore_file: null
        restore_map_location: null
        sampling_device: cpu
        save_folder: null
        share_policy_params: false
        soft_target_update: true
        train_device: cpu
model_config:
    value:
        _is_critic: false
        activation_class: torch.nn.modules.activation.Tanh
        activation_kwargs: null
        layer_class: torch.nn.modules.linear.Linear
        norm_class: null
        norm_kwargs: null
        num_cells:
            - 256
            - 256
model_name:
    value: mlp
on_policy:
    value: true
seed:
    value: 1
task_config:
    value:
        agents:
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
            - EVChargingEnv
        busses:
            - 634a
            - 634b
            - 634c
            - "645"
            - 675a
            - 675b
            - 675c
            - 670a
            - 670b
            - 670c
            - 684c
        cls: OpenDSSSolver
        control_timedelta: 900
        end_time: 08-13-2020 08:00:00
        feeder_file: ieee_13_dss/IEEE13Nodeckt.dss
        loadshape_file: ieee_13_dss/annual_hourly_load_profile.csv
        max_charge_rate_kw: 7
        minutes_per_step: 15
        num_vehicles: 70
        peak_threshold: 700
        rescale_spaces: false
        start_time: 08-12-2020 20:00:00
        system_load_rescale_factor: 0.9
        unserved_penalty: 1
        vehicle_multiplier: 1
task_name:
    value: evovernight13node
